In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
eda=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\bank (1).csv" ,sep=';')

## **Methods apply on visa_df**

- shape size
- len
- columns
- head
- tail
- isnull
- dtypes
- info

In [4]:
eda

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [5]:
eda.shape

(4521, 17)

In [6]:
eda.size

76857

In [7]:



len(eda)

4521

In [8]:
eda.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [9]:
eda.head(10)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
5,35,management,single,tertiary,no,747,no,no,cellular,23,feb,141,2,176,3,failure,no
6,36,self-employed,married,tertiary,no,307,yes,no,cellular,14,may,341,1,330,2,other,no
7,39,technician,married,secondary,no,147,yes,no,cellular,6,may,151,2,-1,0,unknown,no
8,41,entrepreneur,married,tertiary,no,221,yes,no,unknown,14,may,57,2,-1,0,unknown,no
9,43,services,married,primary,no,-88,yes,yes,cellular,17,apr,313,1,147,2,failure,no

In [10]:
eda.tail()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [11]:
eda.isnull()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4517,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4518,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4519,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4520,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
eda.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [13]:
eda.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

In [14]:
eda.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [15]:
data_types=eda.dtypes
data_types

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [16]:
type(data_types)

pandas.core.series.Series

- series type has with out column names
- we can directly apply math operation
- series is a kind of dictionary means key-value pair

In [18]:
d1=data_types.keys()

In [19]:
d2=data_types.values

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
data=zip(d1,d2)
data_types=pd.DataFrame(data,columns=['column','type'])
data_types

       column    type
0         age   int64
1         job  object
2     marital  object
3   education  object
4     default  object
5     balance   int64
6     housing  object
7        loan  object
8     contact  object
9         day   int64
10      month  object
11   duration   int64
12   campaign   int64
13      pdays   int64
14   previous   int64
15   poutcome  object
16          y  object

In [22]:
data_types.to_csv('data_types.csv',index=False)

**Task-2**

- i want separate catagorical and numerical columns

In [24]:
for i,j in zip(d1,d2):
    print(i,j)

age int64
job object
marital object
education object
default object
balance int64
housing object
loan object
contact object
day int64
month object
duration int64
campaign int64
pdays int64
previous int64
poutcome object
y object

In [25]:
d1=data_types.keys()

In [26]:
d2=data_types.values

In [27]:
cat=[]
num=[]
for i,j in dict(d1,d2):
    if i=='object':
        cat.append(i)
    else:
        num.append(j)

print(cat)
print(num)

[]
[array(['age', dtype('int64')], dtype=object), array(['job', dtype('O')], dtype=object)]

In [76]:
cat = []
num = []
for i, j in dict(data_types).items():
    if i == 'object':
        print('=============================')

        cat.append(i)

    else:

        num.append(j)  # Append the corresponding value from d1 to num
print(cat)
print(num)

[]
[0           age
1           job
2       marital
3     education
4       default
5       balance
6       housing
7          loan
8       contact
9           day
10        month
11     duration
12     campaign
13        pdays
14     previous
15     poutcome
16            y
Name: column, dtype: object, 0      int64
1     object
2     object
3     object
4     object
5      int64
6     object
7     object
8     object
9      int64
10    object
11     int64
12     int64
13     int64
14     int64
15    object
16    object
Name: type, dtype: object]

In [29]:
cat=[key for key,value in zip(d1,d2) if i=='object']
num=[key for key,value in zip(d1,d2) if i!='object']

In [30]:
d1=data_types.keys()

In [31]:
d2=data_types.values

In [32]:
cat=[j for i,j in zip(d1,d2) if i=='object']
num=[j for i,j in zip(d1,d2) if i!='object']
cat,num

([],
 [array(['age', dtype('int64')], dtype=object),
  array(['job', dtype('O')], dtype=object)])

In [33]:
eda.select_dtypes(include='object').columns

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome', 'y'],
      dtype='object')

In [34]:
eda.select_dtypes(exclude='object').columns

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='object')

## **Selection of data**

- we can select data
- take
- loc
- iloc

In [36]:
# select 100,200,300 rows
# select continent,prevailing_wage,case_status
eda.take([100,200,300],axis=0)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
100,36,blue-collar,married,secondary,no,0,yes,no,unknown,6,may,337,1,-1,0,unknown,no
200,34,technician,single,tertiary,no,992,yes,no,cellular,4,may,301,1,88,2,success,no
300,70,retired,divorced,primary,no,4531,no,no,cellular,18,may,445,1,-1,0,unknown,no

In [37]:
cols=[1,4,6]
eda.take(cols,axis=1)

                job default housing
0        unemployed      no      no
1          services      no     yes
2        management      no     yes
3        management      no     yes
4       blue-collar      no     yes
...             ...     ...     ...
4516       services      no     yes
4517  self-employed     yes     yes
4518     technician      no      no
4519    blue-collar      no      no
4520   entrepreneur      no     yes

[4521 rows x 3 columns]

In [38]:
cols=[1,4,6]
rows=[100,200,300]
eda.take(cols,axis=1).take(rows,axis=0)

             job default housing
100  blue-collar      no     yes
200   technician      no     yes
300      retired      no      no

In [39]:
l1=range(2,5)
eda.take(l1,axis=0)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [40]:
l1=range(2,5)
l2=[2,3,4,5]
# l3=[2:5]
eda.take(l1,axis=0)
eda.take(l2,axis=0)
# eda.take(l3,axis=0)
# eda.take(5,axis=0)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
5,35,management,single,tertiary,no,747,no,no,cellular,23,feb,141,2,176,3,failure,no

- Drawback at a time either we can select we can select rows or columns

## **iloc**

In [43]:
eda.iloc[rows,cols]

             job default housing
100  blue-collar      no     yes
200   technician      no     yes
300      retired      no      no

In [44]:
eda.iloc[[100,200,300],[1,4,6]]

             job default housing
100  blue-collar      no     yes
200   technician      no     yes
300      retired      no      no

In [45]:
eda.iloc[[100,200,300]]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
100,36,blue-collar,married,secondary,no,0,yes,no,unknown,6,may,337,1,-1,0,unknown,no
200,34,technician,single,tertiary,no,992,yes,no,cellular,4,may,301,1,88,2,success,no
300,70,retired,divorced,primary,no,4531,no,no,cellular,18,may,445,1,-1,0,unknown,no

In [46]:
eda.iloc[[1,4,6]]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
6,36,self-employed,married,tertiary,no,307,yes,no,cellular,14,may,341,1,330,2,other,no

In [47]:
eda.iloc[100:105,[1,4,6]]

             job default housing
100  blue-collar      no     yes
101   management      no     yes
102   technician      no      no
103     services      no     yes
104   management      no      no

In [48]:
eda.iloc[[100,200,300],1:4]

             job   marital  education
100  blue-collar   married  secondary
200   technician    single   tertiary
300      retired  divorced    primary

In [49]:
eda.iloc[range(1,5),range(1,3)]

           job  marital
1     services  married
2   management   single
3   management  married
4  blue-collar  married

In [50]:
eda.iloc[100]

age                   36
job          blue-collar
marital          married
education      secondary
default               no
balance                0
housing              yes
loan                  no
contact          unknown
day                    6
month                may
duration             337
campaign               1
pdays                 -1
previous               0
poutcome         unknown
y                     no
Name: 100, dtype: object

In [51]:
eda.iloc[[100,200,300],['loan']]

IndexError: .iloc requires numeric indexers, got ['loan']

In [ ]:
eda.loc[[100,200,300],['loan']]

## **How to select the columns**

- always whenever you open the new notebook
- import the packages
- step-2 read the data