## **Encoding**

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
visa_df=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")

In [4]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [5]:
cat=visa_df.select_dtypes(include='object').columns
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [6]:
num=visa_df.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

## **Mapmethod**

In [8]:
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [9]:
dict1={'Certified':0,'Denied':1}
dict1

{'Certified': 0, 'Denied': 1}

In [10]:
visa_df['case_status_map']=visa_df['case_status'].map(dict1)

In [11]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,case_status_map
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified,0

In [12]:
visa_df=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns
visa_df,cat,num

(         case_id continent education_of_employee has_job_experience  \
 0         EZYV01      Asia           High School                  N
 1         EZYV02      Asia              Master's                  Y
 2         EZYV03      Asia            Bachelor's                  N
 3         EZYV04      Asia            Bachelor's                  N
 4         EZYV05    Africa              Master's                  Y
 ...          ...       ...                   ...                ...
 25475  EZYV25476      Asia            Bachelor's                  Y
 25476  EZYV25477      Asia           High School                  Y
 25477  EZYV25478      Asia              Master's                  Y
 25478  EZYV25479      Asia              Master's                  Y
 25479  EZYV25480      Asia            Bachelor's                  Y

       requires_job_training  no_of_employees  yr_of_estab  \
 0                         N            14513         2007
 1                         N             2412         2002
 2                         Y            44444         2008
 3                         N               98         1897
 4                         N             1082         2005
 ...                     ...              ...          ...
 25475                     Y             2601         2008
 25476                     N             3274         2006
 25477                     N             1121         1910
 25478                     Y             1918         1887
 25479                     N             3195         1960

       region_of_employment  prevailing_wage unit_of_wage full_time_position  \
 0                     West         592.2029         Hour                  Y
 1                Northeast       83425.6500         Year                  Y
 2                     West      122996.8600         Year                  Y
 3                     West       83434.0300         Year                  Y
 4                    South      149907.3900         Year                  Y
 ...                    ...              ...          ...                ...
 25475                South       77092.5700         Year                  Y
 25476            Northeast      279174.7900         Year                  Y
 25477                South      146298.8500         Year                  N
 25478                 West       86154.7700         Year                  Y
 25479              Midwest       70876.9100         Year                  Y

       case_status
 0          Denied
 1       Certified
 2          Denied
 3          Denied
 4       Certified
 ...           ...
 25475   Certified
 25476   Certified
 25477   Certified
 25478   Certified
 25479   Certified

 [25480 rows x 12 columns],
 Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
        'requires_job_training', 'region_of_employment', 'unit_of_wage',
        'full_time_position', 'case_status'],
       dtype='object'),
 Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object'))

In [13]:
labels=visa_df['continent'].unique()
d={}
for i in range (len(labels)):
    d[labels[i]]=i

d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [14]:
visa_df['continent_map']=visa_df['continent'].map(d)

In [15]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,continent_map
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,0
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,0
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,0
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified,0

In [16]:
labels=visa_df['continent'].unique()
d={labels[i]:i for i in range(len(labels))}
visa_df['continent']=visa_df['continent'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,continent_map
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,0
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,0
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,0
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,0
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified,0
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified,0
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified,0
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified,0
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified,0

In [17]:
visa_df=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [34]:
for i in cat[1:]:
    labels=visa_df[i].unique()
    d={labels[i]:i for i in range(len(labels))}
    visa_df[i]=visa_df[i].map(d)

In [36]:
d

{'Denied': 0, 'Certified': 1}

In [38]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,0,0,0,14513,2007,0,592.2029,0,0,0
1,EZYV02,0,1,1,0,2412,2002,1,83425.6500,1,0,1
2,EZYV03,0,2,0,1,44444,2008,0,122996.8600,1,0,0
3,EZYV04,0,2,0,0,98,1897,0,83434.0300,1,0,0
4,EZYV05,1,1,1,0,1082,2005,2,149907.3900,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,2,1,1,2601,2008,2,77092.5700,1,0,1
25476,EZYV25477,0,0,1,0,3274,2006,1,279174.7900,1,0,1
25477,EZYV25478,0,1,1,0,1121,1910,2,146298.8500,1,1,1
25478,EZYV25479,0,1,1,1,1918,1887,0,86154.7700,1,0,1
25479,EZYV25480,0,2,1,0,3195,1960,3,70876.9100,1,0,1

## **LabelEncoder**

In [47]:
import sklearn
sklearn

In [49]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(visa_df['case_status'])

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

In [53]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['case_data']=le.fit_transform(visa_df['case_status'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,case_data
0,EZYV01,0,0,0,0,14513,2007,0,592.2029,0,0,0,0
1,EZYV02,0,1,1,0,2412,2002,1,83425.6500,1,0,1,1
2,EZYV03,0,2,0,1,44444,2008,0,122996.8600,1,0,0,0
3,EZYV04,0,2,0,0,98,1897,0,83434.0300,1,0,0,0
4,EZYV05,1,1,1,0,1082,2005,2,149907.3900,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,2,1,1,2601,2008,2,77092.5700,1,0,1,1
25476,EZYV25477,0,0,1,0,3274,2006,1,279174.7900,1,0,1,1
25477,EZYV25478,0,1,1,0,1121,1910,2,146298.8500,1,1,1,1
25478,EZYV25479,0,1,1,1,1918,1887,0,86154.7700,1,0,1,1
25479,EZYV25480,0,2,1,0,3195,1960,3,70876.9100,1,0,1,1

In [55]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:
    visa_df[i]=le.fit_transform(visa_df[i])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,case_data
0,EZYV01,0,0,0,0,14513,2007,0,592.2029,0,0,0,0
1,EZYV02,0,1,1,0,2412,2002,1,83425.6500,1,0,1,1
2,EZYV03,0,2,0,1,44444,2008,0,122996.8600,1,0,0,0
3,EZYV04,0,2,0,0,98,1897,0,83434.0300,1,0,0,0
4,EZYV05,1,1,1,0,1082,2005,2,149907.3900,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,2,1,1,2601,2008,2,77092.5700,1,0,1,1
25476,EZYV25477,0,0,1,0,3274,2006,1,279174.7900,1,0,1,1
25477,EZYV25478,0,1,1,0,1121,1910,2,146298.8500,1,1,1,1
25478,EZYV25479,0,1,1,1,1918,1887,0,86154.7700,1,0,1,1
25479,EZYV25480,0,2,1,0,3195,1960,3,70876.9100,1,0,1,1

In [57]:
visa_df=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [59]:
pd.get_dummies(visa_df,dtype=int)

,no_of_employees,yr_of_estab,prevailing_wage,case_id_EZYV01,case_id_EZYV02,case_id_EZYV03,case_id_EZYV04,case_id_EZYV05,case_id_EZYV06,case_id_EZYV07,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,14513,2007,592.2029,1,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
1,2412,2002,83425.6500,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
2,44444,2008,122996.8600,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,98,1897,83434.0300,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,1082,2005,149907.3900,0,0,0,0,1,0,0,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,2601,2008,77092.5700,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,3274,2006,279174.7900,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
25477,1121,1910,146298.8500,0,0,0,0,0,0,0,...,1,0,0,0,0,1,1,0,1,0
25478,1918,1887,86154.7700,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
25479,3195,1960,70876.9100,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0

In [61]:
cols=cat[1:]
df2=pd.get_dummies(visa_df,columns=cols,dtype=int)
df2

,case_id,no_of_employees,yr_of_estab,prevailing_wage,continent_Africa,continent_Asia,continent_Europe,continent_North America,continent_Oceania,continent_South America,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,EZYV01,14513,2007,592.2029,0,1,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
1,EZYV02,2412,2002,83425.6500,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
2,EZYV03,44444,2008,122996.8600,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,EZYV04,98,1897,83434.0300,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,EZYV05,1082,2005,149907.3900,1,0,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,2601,2008,77092.5700,0,1,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,EZYV25477,3274,2006,279174.7900,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
25477,EZYV25478,1121,1910,146298.8500,0,1,0,0,0,0,...,1,0,0,0,0,1,1,0,1,0
25478,EZYV25479,1918,1887,86154.7700,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
25479,EZYV25480,3195,1960,70876.9100,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0

In [65]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Step 1: Encode continent into numbers
le = LabelEncoder()
visa_df['continent_encoded'] = le.fit_transform(visa_df['continent'])

# Step 2: Scale encoded continent
scaler = StandardScaler()
visa_df['continent_scaled'] = scaler.fit_transform(visa_df[['continent_encoded']])

visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,continent_encoded,continent_scaled
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,1,-0.540533
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,1,-0.540533
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,1,-0.540533
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,1,-0.540533
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,0,-1.542264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified,1,-0.540533
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified,1,-0.540533
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified,1,-0.540533
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified,1,-0.540533
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified,1,-0.540533

In [69]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
df2['continent'] = ss.fit_transform(df2[['continent']])

KeyError: "None of [Index(['continent'], dtype='object')] are in the [columns]"