## **- Under EDA**

**- Data Analysis**
     - Quick Checks
     - how to select the column
     - we understood the difference bet df vs series vs values
     - Frequency Table
     - bar charts
     - pie charts
     - histogram
     - Distribution plots                                                                                                                 
     - outliers
     - Deal with Outliers
     - bi variate analysis
     - multivairate analysis
     - heatmaps
**- Feature enginearing**
     - Encoding
     - Scaling
     - Transformation
**- Feature selection(How to select important features)**

**Encoding**

- convert catagorical data to numerical data
- ML algorithem developed by maths
- maths needs numbers
- it is very important we need to convert categorical data to numerical
  - map
  - np.where
  - LabelEncoder
  - OneHotcoder

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [5]:
cat=df1.select_dtypes(include='object').columns
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [6]:
num=df1.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

## **Map Method**

In [8]:
df1['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [9]:
dict1={'Certified':0,'Denied':1}
dict1

{'Certified': 0, 'Denied': 1}

In [10]:
df1['case_status_map']=df1['case_status'].map(dict1)

In [11]:
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,case_status_map
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified,0

In [12]:
df1['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [13]:
dict2={'Africa':0,'Asia':1,'Europe':3,'North America':4,'Oceania':5,'South America':6}
dict2

{'Africa': 0,
 'Asia': 1,
 'Europe': 3,
 'North America': 4,
 'Oceania': 5,
 'South America': 6}

In [14]:
df1['continent_map']=df1['continent'].map(dict2)

In [15]:
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,case_status_map,continent_map
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,1,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,0,1
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,1,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,1,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified,0,1
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified,0,1
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified,0,1
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified,0,1
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified,0,1

In [16]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=df1.select_dtypes(include='object').columns
num=df1.select_dtypes(exclude='object').columns

In [17]:
cat=df1.select_dtypes(include='object').columns
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [18]:
num=df1.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [19]:
labels=df1['continent'].unique()
d={}
for i in range(len(labels)):
    d[labels[i]]=i

d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [20]:
labels=df1['continent'].unique()
d={labels[i]:i for i in range(len(labels))}
df1['continent']=df1['continent'].map(d)
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [3]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=df1.select_dtypes(include='object').columns
num=df1.select_dtypes(exclude='object').columns
df1,cat,num

(         case_id continent education_of_employee has_job_experience  \
 0         EZYV01      Asia           High School                  N
 1         EZYV02      Asia              Master's                  Y
 2         EZYV03      Asia            Bachelor's                  N
 3         EZYV04      Asia            Bachelor's                  N
 4         EZYV05    Africa              Master's                  Y
 ...          ...       ...                   ...                ...
 25475  EZYV25476      Asia            Bachelor's                  Y
 25476  EZYV25477      Asia           High School                  Y
 25477  EZYV25478      Asia              Master's                  Y
 25478  EZYV25479      Asia              Master's                  Y
 25479  EZYV25480      Asia            Bachelor's                  Y

       requires_job_training  no_of_employees  yr_of_estab  \
 0                         N            14513         2007
 1                         N             2412         2002
 2                         Y            44444         2008
 3                         N               98         1897
 4                         N             1082         2005
 ...                     ...              ...          ...
 25475                     Y             2601         2008
 25476                     N             3274         2006
 25477                     N             1121         1910
 25478                     Y             1918         1887
 25479                     N             3195         1960

       region_of_employment  prevailing_wage unit_of_wage full_time_position  \
 0                     West         592.2029         Hour                  Y
 1                Northeast       83425.6500         Year                  Y
 2                     West      122996.8600         Year                  Y
 3                     West       83434.0300         Year                  Y
 4                    South      149907.3900         Year                  Y
 ...                    ...              ...          ...                ...
 25475                South       77092.5700         Year                  Y
 25476            Northeast      279174.7900         Year                  Y
 25477                South      146298.8500         Year                  N
 25478                 West       86154.7700         Year                  Y
 25479              Midwest       70876.9100         Year                  Y

       case_status
 0          Denied
 1       Certified
 2          Denied
 3          Denied
 4       Certified
 ...           ...
 25475   Certified
 25476   Certified
 25477   Certified
 25478   Certified
 25479   Certified

 [25480 rows x 12 columns],
 Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
        'requires_job_training', 'region_of_employment', 'unit_of_wage',
        'full_time_position', 'case_status'],
       dtype='object'),
 Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object'))

In [5]:
for i in cat[1:]:
    labels=df1[i].unique()
    d={labels[i]:i for i in range(len(labels))}
    df1[i]=df1[i].map(d)
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,0,0,0,14513,2007,0,592.2029,0,0,0
1,EZYV02,0,1,1,0,2412,2002,1,83425.6500,1,0,1
2,EZYV03,0,2,0,1,44444,2008,0,122996.8600,1,0,0
3,EZYV04,0,2,0,0,98,1897,0,83434.0300,1,0,0
4,EZYV05,1,1,1,0,1082,2005,2,149907.3900,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,2,1,1,2601,2008,2,77092.5700,1,0,1
25476,EZYV25477,0,0,1,0,3274,2006,1,279174.7900,1,0,1
25477,EZYV25478,0,1,1,0,1121,1910,2,146298.8500,1,1,1
25478,EZYV25479,0,1,1,1,1918,1887,0,86154.7700,1,0,1
25479,EZYV25480,0,2,1,0,3195,1960,3,70876.9100,1,0,1

## **LabelEncoder**

In [7]:
import sklearn
sklearn

In [9]:
# Step-1 import the package
from sklearn.preprocessing import LabelEncoder
#step-2 save the package
le=LabelEncoder()
# step-3 fit and fit_transform
le.fit_transform(df1['case_status'])

# fit means finding the some values
# transforms means: transform apply those values
#

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

In [26]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=df1.select_dtypes(include='object').columns
num=df1.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df1['case_data']=le.fit_transform(df1['case_status'])
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,case_data
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified,0

In [28]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=df1.select_dtypes(include='object').columns
num=df1.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [29]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df1['continent']=le.fit_transform(df1['continent'])
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [30]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=df1.select_dtypes(include='object').columns
num=df1.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [31]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df1['region_of_employment']=le.fit_transform(df1['region_of_employment'])
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,4,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,2,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,4,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,4,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,3,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,3,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,2,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,3,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,4,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,1,70876.9100,Year,Y,Certified

In [32]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=df1.select_dtypes(include='object').columns
num=df1.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [33]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:
    df1[i]=le.fit_transform(df1[i])
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

## **OnehotEncoder**

## **pd.get_dummies**

In [36]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=df1.select_dtypes(include='object').columns
num=df1.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [37]:
pd.get_dummies(df1,dtype=int)

,no_of_employees,yr_of_estab,prevailing_wage,case_id_EZYV01,case_id_EZYV02,case_id_EZYV03,case_id_EZYV04,case_id_EZYV05,case_id_EZYV06,case_id_EZYV07,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,14513,2007,592.2029,1,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
1,2412,2002,83425.6500,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
2,44444,2008,122996.8600,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,98,1897,83434.0300,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,1082,2005,149907.3900,0,0,0,0,1,0,0,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,2601,2008,77092.5700,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,3274,2006,279174.7900,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
25477,1121,1910,146298.8500,0,0,0,0,0,0,0,...,1,0,0,0,0,1,1,0,1,0
25478,1918,1887,86154.7700,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
25479,3195,1960,70876.9100,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0

In [38]:
cols=cat[1:]
df2=pd.get_dummies(df1,columns=cols,dtype=int)
df2

,case_id,no_of_employees,yr_of_estab,prevailing_wage,continent_Africa,continent_Asia,continent_Europe,continent_North America,continent_Oceania,continent_South America,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,EZYV01,14513,2007,592.2029,0,1,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
1,EZYV02,2412,2002,83425.6500,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
2,EZYV03,44444,2008,122996.8600,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,EZYV04,98,1897,83434.0300,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,EZYV05,1082,2005,149907.3900,1,0,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,2601,2008,77092.5700,0,1,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,EZYV25477,3274,2006,279174.7900,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
25477,EZYV25478,1121,1910,146298.8500,0,1,0,0,0,0,...,1,0,0,0,0,1,1,0,1,0
25478,EZYV25479,1918,1887,86154.7700,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
25479,EZYV25480,3195,1960,70876.9100,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0

In [39]:
from sklearn.preprocessing import StandardScalar
ss=StandardScalar()
df1['continent']=ss.fit_transform(df1['continent'])
df1

ImportError: cannot import name 'StandardScalar' from 'sklearn.preprocessing' (C:\Users\pguru\anaconda3\Lib\site-packages\sklearn\preprocessing\__init__.py)

- Before model Development

- We will do EDA: Exploratary data anlysis
  - Feature(columns)analysis
     - Categorical,Numerical, Outliers analysis, Bivariate, Multivarite
     - We will get the insight
  - Feature Engineering
     - we will modify the the data
     - Models developed by maths
     - Encoding : Convert categorical data to Numerical Variables
     - Scaling : All the numerical columns makes under one scale
     - Transformations : All the maths developed by assumption data follows distribution
       - convert skewed distribution to Normal
  - Feature selection

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sns

In [8]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=df1.select_dtypes(include='object').columns
num=df1.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

## **Map Method

- create a dictionary labels as keys, numbers a values
- in python index start with 0
- Case status has two labels we need two values 0 and 1
- Certified becomes 0
- Denied becomes 1

In [12]:
df1['case_status'].nunique()

2

In [14]:
df1['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [16]:
d={'Certified':0,'Denied':1}
df1['case_status']=df1['case_status'].map(d)

In [18]:
d

{'Certified': 0, 'Denied': 1}

In [20]:
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [22]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=df1.select_dtypes(include='object').columns
num=df1.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [34]:
labels=df1['continent'].unique()
d={}
for i in range(len(labels)):
    d[labels[i]]=i

d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [36]:
labels=df1['continent'].unique()
d={labels[i]:i for i in range(len(labels))}
    #Key             #value
df1['continent']=df1['continent'].map(d)

In [38]:
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [42]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=df1.select_dtypes(include='object').columns
num=df1.select_dtypes(exclude='object').columns
for i in cat[1:]:
    labels=df1[i].unique()
    d={labels[i]:i for i in range(len(labels))}
    df1[i]=df1[i].map(d)
df1

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,0,0,0,14513,2007,0,592.2029,0,0,0
1,EZYV02,0,1,1,0,2412,2002,1,83425.6500,1,0,1
2,EZYV03,0,2,0,1,44444,2008,0,122996.8600,1,0,0
3,EZYV04,0,2,0,0,98,1897,0,83434.0300,1,0,0
4,EZYV05,1,1,1,0,1082,2005,2,149907.3900,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,2,1,1,2601,2008,2,77092.5700,1,0,1
25476,EZYV25477,0,0,1,0,3274,2006,1,279174.7900,1,0,1
25477,EZYV25478,0,1,1,0,1121,1910,2,146298.8500,1,1,1
25478,EZYV25479,0,1,1,1,1918,1887,0,86154.7700,1,0,1
25479,EZYV25480,0,2,1,0,3195,1960,3,70876.9100,1,0,1

## **prepare  all methods in one notes**

- Fequency table
- subplot using for loop
-

## **LabelIEncoder**

- Sickit-learn(sklearn)
- sklearn library is a heart of machine learning in python
- mLlib is heart of machine learning in pyspark
- sklearn (library)
   - preprocess (Class)
      - LabelEncoder(Method)

- fit : calculate something
- fit_transform : we are modify the values because of calculated one

In [49]:
df1=pd.read_csv(r"F:\Omkar_sir_files\CSV_Files\Visadataset (1).csv")
cat=df1.select_dtypes(include='object').columns
num=df1.select_dtypes(exclude='object').columns
from sklearn.preprocessing import LabelEncoder #read the method  
le=LabelEncoder()                       #save the method
le.fit_transform(df1['case_status'])  # apply fit transform

array([1, 0, 1, ..., 0, 0, 0])